sudo: required
language: cpp
compiler:
    - gcc
    - clang
os:
    - linux
notifications:
    email:
        recipients:
            - dilawar.s.rajput@gmail.com
            - bhalla@ncbs.res.in
            - hrani@ncbs.res.in
            - ray.subhasis@gmail.com
        on_success: change
        on_failure: always

env:
    - CTEST_MODEL=Nightly
cache: apt

matrix:
    allow_failures:
        compiler:
            - clang

before_script:
    - sudo apt-get install -qq g++ arduino arduino-mk
    - sudo apt-get install -qq make cmake
    - sudo apt-get install -qq  python-numpy python-matplotlib python-networkx

install:
    - echo "nothing to do here"

script:
    - # checking if any python3 incompatible file is in the source tree.
    - python2 -m compileall -q .
    - # Then run the old make scripts
    - make -f Makefile.arduino 
    - cd ./PointGreyCamera && cmake . && make 
    - echo "All done. Phew"
