sudo: required
dist: bionic
language: python
compiler: gcc
cache: apt

python:
    - 3.6

install:
    - echo "nothing to do here"

script:
    - # checking if any python3 incompatible file is in the source tree.
    - sudo ./bootstrap.sh && cd ..
    - python3 -m compileall -q .
    - ./.travis_build.sh
    - echo "All done. Phew"
