site_name: MouseBehaviour
repo_url: https://github.com/BhallaLab/MouseBehaviour
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - c++
        - python
nav:
    - Home: index.md
    - Build pipeline: build_pipeline.md
    - Run pipeline: run_pipeline.md
    - Using GUI: gui.md
    - EDA (PCB, Circuit Board, Arduino): eda.md
    - CAD (3d designs etc): cad.md

extra_css: [extra.css]

markdown_extensions:
    - admonition
    - toc
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
    
