// These variables are generated by cmake + /home/dilawars/Work/MouseBehaviour/Protocols/protocol_to_config.py
#define PROTO_CODE      "Hr5"
#define PROTO_SessionType      18
#define PROTO_Description      "Overlap CS US"
#define PROTO_PreStimDuration_LOW      8000
#define PROTO_PreStimDuration_HIGH      8000
#define PROTO_CSDuration      250
#define PROTO_CSValue      "TONE"
#define PROTO_TraceDuration      0
#define PROTO_USDuration      50
#define PROTO_USValue      "SHOCK"
#define PROTO_PostStimDuration      8000
#define PROTO_NextProbeTrial_LOW      6
#define PROTO_NextProbeTrial_HIGH      10
#define PROTO_NumTrialsInABlock      60
#define PROTO_CSUSOverlap      50
#define PROTO_Comments      "Overlap from the END of CS."