// These variables are generated by cmake and /home/dilawars/Work/MouseBehaviour/Protocols/protocol_to_config.py
// Input file: variables are generated by cmake + /home/dilawars/Work/MouseBehaviour/Protocols/BehaviourProtocols.yml


#ifndef XXX_CONFIG_H
#define XXX_CONFIG_H


#include "callback.h"    // pre-defined callback. 

// PROTOCOL: Hr1
#define PROTO_CODE "Hr1"
#define PROTO_NumTrialsInABlock 60
// Description: Hr1
typedef struct Interval {
    const char* name;
    int start;
    int end;
    const char* value;
    void (*callbackStart) (const callback_data_t* data, void*);
    void (*callbackEnd) (const callback_data_t* data, void*);
} interval_t;
interval_t intervalPRE = { .name="PRE", .start = 0, .end = 8000, .value = "NONE" , .callbackStart = funcPREStart, .callbackEnd = funcPREEnd };
interval_t intervalCS = { .name="CS", .start = 8000, .end = 8050, .value = "PUFF" , .callbackStart = funcCSStart, .callbackEnd = funcCSEnd };
interval_t intervalTRACE = { .name="TRACE", .start = 8050, .end = 8300, .value = "NONE" , .callbackStart = funcTRACEStart, .callbackEnd = funcTRACEEnd };
interval_t intervalUS = { .name="US", .start = 8300, .end = 8350, .value = "TONE" , .callbackStart = funcUSStart, .callbackEnd = funcUSEnd };
interval_t intervalPOST = { .name="POST", .start = 8350, .end = 16350, .value = "NONE" , .callbackStart = funcPOSTStart, .callbackEnd = funcPOSTEnd };


#endif