// These variables are generated by cmake and /home/dilawars/Work/MouseBehaviour/Protocols/protocol_to_config.py
// Input file: variables are generated by cmake + /home/dilawars/Work/MouseBehaviour/Protocols/BehaviourProtocols.yml


#ifndef XXX_CONFIG_H
#define XXX_CONFIG_H


#include "callback.h"    // pre-defined callback. 

// PROTOCOL: Hr1
#define PROTO_CODE Hr1
#define PROTO_NumTrialsInABlock 60
// Description: Hr1
struct Interval {
    char name[5];
    int start;
    int end;
    char value[10];
    void (*callbackStart) ();
    void (*callbackEnd) ();
};
Interval intervals_[5];
struct Interval intPRE = { .name="PRE", .start = 0, .end = 8000, .value = "NONE" , .callbackStart = funcPREStart, .callbackEnd = funcPREEnd };
intervals_[0] = intPRE;
struct Interval intCS = { .name="CS", .start = 8000, .end = 8050, .value = "PUFF" , .callbackStart = funcCSStart, .callbackEnd = funcCSEnd };
intervals_[1] = intCS;
struct Interval intTRACE = { .name="TRACE", .start = 8050, .end = 8300, .value = "NONE" , .callbackStart = funcTRACEStart, .callbackEnd = funcTRACEEnd };
intervals_[2] = intTRACE;
struct Interval intUS = { .name="US", .start = 8300, .end = 8350, .value = "TONE" , .callbackStart = funcUSStart, .callbackEnd = funcUSEnd };
intervals_[3] = intUS;
struct Interval intPOST = { .name="POST", .start = 8350, .end = 16350, .value = "NONE" , .callbackStart = funcPOSTStart, .callbackEnd = funcPOSTEnd };
intervals_[4] = intPOST;


#endif