// These variables are generated by cmake + /home/dilawars/Work/BhallaLab/MouseBehaviour/Protocols/protocol_to_config.py
#define PROTO_NextProbeTrial_LOW      6
#define PROTO_PreStimDuration_LOW      8000
#define PROTO_CODE      "So1"
#define PROTO_SessionType      5
#define PROTO_NextProbeTrial_HIGH      10
#define PROTO_Description      "tone+puff1"
#define PROTO_PreStimDuration_HIGH      8000
#define PROTO_Comments      "soumya"
#define PROTO_TraceDuration      250
#define PROTO_CSDuration      50
#define PROTO_CSValue      "TONE"
#define PROTO_USDuration      50
#define PROTO_PostStimDuration      8000
#define PROTO_NumTrialsInABlock      60
#define PROTO_USValue      "PUFF"